### ISSUE TITLE
DB Error 1064 Es_es.phar

### ISSUE THREAD

**Issue by xtura** [rowlandan25/osTicket-Modules#23]
Hi Andrew,

Thank you for your quick response. 

Again, Clean install of 1.9.4 in Spanish with 1010. Now the following errors occurs.

[INSERT INTO ost_mod_logs (logName, logDetail, logType) VALUES ('Query Failed', 'Failed to execute query: INSERT INTO ost_form_field (form_id, label, required, name, sort, edit_mask, created, updated) VALUES (, 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())', 3)]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())', 3)' at line 1<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[INSERT INTO os...')<br />
#1 (raíz)/include/staff/modules.inc.php(76): db_query('INSERT INTO ost...')<br />
#2 (raíz)/include/staff/modules.inc.php(354): logEntry('Query Failed', 'Failed to execu...', 3)<br />
#3 (raíz)/include/staff/modules.inc.php(158): build1008()<br />
#4 (raíz)/include/staff/modules.inc.php(26): initialize('status')<br />
#5 (raíz)/scp/settings.php(48): update_modules()<br />
#6 {main}

And another....

[INSERT INTO ost_form_field (form_id, label, required, name, sort, edit_mask, created, updated) VALUES (, 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())' at line 1<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[INSERT INTO os...')<br />
#1 (raíz)/include/staff/modules.inc.php(354): db_query('INSERT INTO ost...')<br />
#2 (raíz)/include/staff/modules.inc.php(158): build1008()<br />
#3 (raíz)/include/staff/modules.inc.php(26): initialize('status')<br />
#4 (raíz)/scp/settings.php(48): update_modules()<br />
#5 {main}

Best regards,

roger

**Comment by kyle0440** [comment]
I got the same error. En-us, though.

**Comment by oneil89** [comment]
Has anyone a solution?
