### ISSUE TITLE
1.9.7 compatibility

### ISSUE THREAD

**Issue by expeepit** [rowlandan25/osTicket-Modules#26]
hi, i've just tried uploading Build 1010 (Alpha) for osTicket v1.9.4 into my v1.9.7 installation but the Modules tab does not have any modules in it to enable...
![capture](https://cloud.githubusercontent.com/assets/11963921/7161983/ff68b516-e389-11e4-8787-6f83006eed3c.PNG)

Have I done something stupid ???

**Comment by johnhwyman** [comment]
I uploaded it and it worked fine. Both with and existing installation that I upgraded and a totally new installation of 1.9.7.
Maybe you copied the files incorrectly, flush the cache, etc.

**Comment by expeepit** [comment]
Thanks for the quick reply; I've restarted the web server (Ubuntu Apache2) and have tried from a couple of different client machines and using different browsers (Firefox and IE), but all we see is as per the screenshot in my original post.  Looks like it's seeing the ChangeLog module, but no others.

Not sure how I can have uploaded the files incorrectly... they're all there (with appropriate time stamps) and permissions...

**Comment by codekmarv** [comment]
Hi, Same here, I can't see the  Initialize Now box anywhere in the module tab. Using latest version, 19.7

**Comment by codekmarv** [comment]
Any idea?

**Comment by expeepit** [comment]
I didn't manage to get this module thing to work, so ended up fudging the tickets.inc.php file myself.  It's not the prettiest of solutions but it does at least display the ticket status.  Here's what I did...

/include/staff/tickets.inc.php
Copy the Table Headers from lines 384 > 386, which display the ticket Status when searching, above the IF statement (to start at line 382).
Comment out lines 384 > 386 so that a duplicate column of ticket status's is not displayed when searching.

Then do the same thing again for the table data, down on lines 489 ish...  copy the few lines relating to ticket status stuff to above the IF statement and comment them out from below the IF statement.

Hope that helps !

**Comment by codekmarv** [comment]
Thanks. I'll have to do that too. Thanks a lot for your help.

**Comment by ghost** [comment]
DB Error #1062

[INSERT INTO ost_mod_list (moduleName,  modulePath) VALUES ('Statuses',  'modstat')] Duplicate entry 'Statuses' for key 'moduleName'

 ---- Trace ----
 #0 (racine)/include/mysqli.php(177): osTicket->logDBError('DB Error #1062',  '[INSERT INTO os...')
 #1 (racine)/include/staff/modules.inc.php(306): db_query('INSERT INTO ost...')
 #2 (racine)/include/staff/modules.inc.php(171): build1008()
 #3 (racine)/include/staff/modules.inc.php(26): initialize('status')
 #4 (racine)/scp/settings.php(48): update_modules()
 #5 {main}

I have this error when i try to use Module with OsTicket 1.9.7

**Comment by engtechgrp** [comment]
@expeepit @codekmarv  
I just tried to load this myself for the first time and ran into the same issue of not seeing any place to initialize the modules.  Then, I realized that I overlooked the instructions and just assumed that the modules page on the admin section was the right place to go.  It's not.  As the instructions say, go to Admin -> SETTINGS -> Modules

"After the files are copied over and osTicket is installed, go to the Admin Panel -> Settings -> Modules. Here, you can initialize each individual module for use and choose whether they are enabled or disabled for use."

**Comment by expeepit** [comment]
Thanks engtechgrp !!

**Comment by oneil89** [comment]
hey Guys,

i have an error an cannot save the seetings

The settings can not be updated - Please correct the errors and try again

SQL Error

---

[SELECT propertyName, valueCurrent FROM ost_mod_status_object_properties WHERE objectId=]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br /> <br />
---- Ablaufverfolgung ----<br />
#0 D:\xampp\htdocs\OSTicket\include\mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT propert...')<br />
#1 D:\xampp\htdocs\OSTicket\include\staff\modules-modstat.inc.php(48): db_query('SELECT property...')<br />
#2 D:\xampp\htdocs\OSTicket\scp\module.php(143): include_once('D:\xampp\htdocs...')<br />
#3 {main}

what is the problem?

**Comment by jmdziba** [comment]
I have osTicket-Modules-1.1.07-alpha.1010 installed on osTicket (v1.9.11).  I am getting the following error message delivered to my email:

DB Error #1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT id, pro...')<br />
#1 (root)/include/staff/modules-shape.inc.php(52): db_query('SELECT id, prop...')<br />
#2 (root)/scp/module.php(143): include_once('/home/interpol/...')<br />
#3 {main}

Could use some help to get this to go away.  Otherwise, everything seems to be working ok.

**Comment by SSPLTD** [comment]
Just a thanks for this module. Installed and works a treat on our installation V1.9.12.

This is exactly the thing we need!
