### ISSUE TITLE
Modules tab ?

### ISSUE THREAD

**Issue by ititservice** [rowlandan25/osTicket-Modules#28]
Hello ...
I install version 1.1.07 on my osticket v1.9.4 but the modules tab is empty. Is there anything i can do ?
Also a DB error appears:
[SELECT id, propertyName, valueCurrent FROM perfectj_mod_status_object_properties WHERE objectId=]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br />
<br />
---- Καταγραφή Σφάλματος (Backtrace) ----<br />
#0 (αρχικό σημείο)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT id, pro...')<br />
#1 (αρχικό σημείο)/include/staff/modules-shape.inc.php(52): db_query('SELECT id, prop...')<br />
#2 (αρχικό σημείο)/scp/module.php(143): include_once('/home/perfectj/...')<br />
#3 {main}

Thank you in advance

![module](https://cloud.githubusercontent.com/assets/13537410/8929833/0e201344-3531-11e5-9e19-6cd96bf479da.jpg)

**Comment by ititservice** [comment]
anyone ?
